### PR TITLE
IRVE: set schema and filesize on update

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Update the script to:
- set the `schema` attribute when creating a monthly resource
- set the `filesize` attribute on the latest permalink to enable file preview

### CODE REVIEW

**Comment by abulte** [comment]
🙏

**Comment by AntoineAugusti** [comment]
Has this been deployed to production? I noticed that for the August resource the `schema` has not been set

**Comment by abulte** [comment]
Nope, I forgot to pull :-(

**Comment by AntoineAugusti** [comment]
No worries, glad we've got an explanation

**Pull request merged**
